services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
      args:
        # For EC2: Use http://YOUR-EC2-IP:5000
        # For local: Use http://localhost:5000 (default in App.js)
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000}
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
